### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by cyb3113** [VivaLasVenus/VivaLasVenus#8]
Viva Las Venus website

**Comment by vmesel** [comment]
@cyb3113 what do you expect for the website? Just a simple HTML? looking forward to this issue!

**Comment by cyb3113** [comment]
@vmesel can you help me to think in something ? Can we include a chatbot :) ?

**Comment by vmesel** [comment]
@cyb3113 yep, hell yeah!

- We could do primarily a website containing basic info about data _detoxing_ and how people should get started.

- For the chatbot, we need to think what should be the main dialog and which tools we should use! Thinking of using google DialogFlow for better maintenance and quick mods. What do you think?

**Comment by cyb3113** [comment]
I'll think in some texts to the website. Maybe something like this [https://thimbleprojects.org/amira/283780/#overview](url)
You understand way better than me about chatbots, so it's up to you  :)

**Comment by bax-uva** [comment]
Hi, I would like to contribute to the website. I'm a frontend programmer, can help you think about this interface.

**Comment by cyb3113** [comment]
@bax-uva Thanks a lot!
Your help is very welcome! I have some ideas but please, share yours! Let's make an awesome website :)

**Comment by bax-uva** [comment]
nice! i have some questions. 
- is there a content already? the link you posted previously is not working. 
- will it be possible to buy hosting and a domain? cause we have also the possibility of hosting it on github pages for free if it's all static (but the bot, as far as i know requires other languages that github pages doesn't support)
- what would be the chatbot specifically for?

**Comment by cyb3113** [comment]
Hi @bax-uva 

- the link is this: https://thimbleprojects.org/amira/301467/#overview I'm thinking in a structure like this.  An area to explain the project, for our events and their documentation (everything is Creative Commons Attribution Share Alike 4.0) and a kind of blog (to publish text instead Medium)
- I still working on content. I have lots of ideas but is not plenty organized yet
- Yes, I'm planning to buy hosting and domain in a near future
- It's highly important be a safe website - HTTPS is crucial :) and accessible (i.e. www.codamos.club. There's no JS, because bad to screen reader)
- Chatbot is something @vmesel suggested.  An idea is  something like this https://securityplanner.org/#/ but like a bot 

PS# Please feel super free for any suggestion :)

**Comment by jessicacarneiro** [comment]
Hi @cyb3113! I would like to help with the website! I'm not a professional, but I've built my own website using Jekyll ([http://jessicacarneiro.github.io/](http://jessicacarneiro.github.io/)). I believe it's an easy option to use at first ([https://jekyllrb.com/](https://jekyllrb.com/)). Also, we could have a certificate from [Let's Encrypt](https://letsencrypt.org/)!

:)

**Comment by diemesleno** [comment]
Hi guys, I'm back-end programmer and I would like to help with the website. Normally I use Python (Django/Flask) to develop my websites/systems. 

if you need a domain or host I can help too.

**Comment by cyb3113** [comment]
@diemesleno thanks! 
I'm still developing the content but  I'm thinking in something like this https://thimbleprojects.org/amira/283780/#overview but prettier :)
